In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\archive (10)\IPL.csv")
df.head()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14468\2721491638.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\Lenovo\Downloads\archive (10)\IPL.csv")

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,batting_team_players,bowling_team_players,curr_batter_runs,curr_batter_balls,bowler_wicket,batting_partners,next_batter
0,0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,1,0,"('BB McCullum', 'SC Ganguly')",NaN
1,1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,1,0,"('BB McCullum', 'SC Ganguly')",NaN
2,2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,1,0,"('BB McCullum', 'SC Ganguly')",NaN
3,3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,2,0,"('BB McCullum', 'SC Ganguly')",NaN
4,4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,3,0,"('BB McCullum', 'SC Ganguly')",NaN

In [7]:
df.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'batting_team_players', 'bowling_team_players', 'curr_batter_runs',
       'curr_batter_balls', 'bowler_wicket', 'batting_partners',
       'next_batter'],
      dtype='object')

In [9]:
df.shape

(260920, 65)

In [11]:
df.dtypes

Unnamed: 0            int64
match_id              int64
date                 object
match_type           object
event_name           object
                      ...
curr_batter_runs      int64
curr_batter_balls     int64
bowler_wicket         int64
batting_partners     object
next_batter          object
Length: 65, dtype: object

In [15]:
df

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,batting_team_players,bowling_team_players,curr_batter_runs,curr_batter_balls,bowler_wicket,batting_partners,next_batter
0,0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,1,0,"('BB McCullum', 'SC Ganguly')",NaN
1,1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,1,0,"('BB McCullum', 'SC Ganguly')",NaN
2,2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,1,0,"('BB McCullum', 'SC Ganguly')",NaN
3,3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,2,0,"('BB McCullum', 'SC Ganguly')",NaN
4,4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,"['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...","['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...",0,3,0,"('BB McCullum', 'SC Ganguly')",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,257726,1426312,2024-05-26,T20,Indian Premier League,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,...,59,2,NaN,"['Rahmanullah Gurbaz', 'SP Narine', 'VR Iyer',...","['Abhishek Sharma', 'TM Head', 'RA Tripathi', ...",5,2,0,"('SS Iyer', 'VR Iyer')",NaN
260916,257727,1426312,2024-05-26,T20,Indian Premier League,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,...,60,2,NaN,"['Rahmanullah Gurbaz', 'SP Narine', 'VR Iyer',...","['Abhishek Sharma', 'TM Head', 'RA Tripathi', ...",50,24,0,"('SS Iyer', 'VR Iyer')",NaN
260917,257728,1426312,2024-05-26,T20,Indian Premier League,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,...,61,2,NaN,"['Rahmanullah Gurbaz', 'SP Narine', 'VR Iyer',...","['Abhishek Sharma', 'TM Head', 'RA Tripathi', ...",51,25,0,"('SS Iyer', 'VR Iyer')",NaN
260918,257729,1426312,2024-05-26,T20,Indian Premier League,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,...,62,2,NaN,"['Rahmanullah Gurbaz', 'SP Narine', 'VR Iyer',...","['Abhishek Sharma', 'TM Head', 'RA Tripathi', ...",6,3,0,"('SS Iyer', 'VR Iyer')",NaN
260919,257730,1426312,2024-05-26,T20,Indian Premier League,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,...,63,2,NaN,"['Rahmanullah Gurbaz', 'SP Narine', 'VR Iyer',...","['Abhishek Sharma', 'TM Head', 'RA Tripathi', ...",52,26,0,"('SS Iyer', 'VR Iyer')",NaN

**Data Cleaning**

In [20]:
df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [22]:
df['batting_team'].nunique()

19